import { motion } from "motion/react";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";
import { CardContent } from "@/components/ui/card";
import { HugeiconsIcon } from "@hugeicons/react";
import { ArrowRight01Icon } from "@hugeicons/core-free-icons";

import { webDevRoadmapData } from "@/data/resources/web";

const syllabus = [
  {
    title: "Foundation",
    topics: [
      "Javascript, async nature of JS",
      "Node.js and its runtime",
      "Databases (NoSQL/SQL)",
      "Mongo and Postgres deep dive",
      "Typescript beginner to advance",
    ],
  },
  {
    title: "Backend",
    topics: [
      "Backend communication protocols",
      "Express basic to advance",
      "ORMs",
      "Middlewares, routes, status codes, global catches",
      "Zod",
      "MonoRepos, turborepo",
      "Serverless Backends",
      "OpenAPI Spec",
      "Autogenerated clients",
      "Authentication using external libraries",
      "Scaling Node.js, performance benchmarks",
      "Deploying npm packages",
    ],
  },
  {
    title: "Frontend",
    topics: [
      "Reconcilers and Frontend frameworks",
      "React beginner to advance",
      "Internals of state, Context API",
      "State management using Recoil",
      "CSS you need to know of, Flexbox, basic styling",
      "Frontend UI frameworks, Deep dive into Tailwind",
      "Containerization, Docker",
      "Next.js",
      "Custom hooks",
      "In house auth using NextAuth",
    ],
  },
  {
    title: "Basic Devops",
    topics: [
      "Docker end to end",
      "Deploying to AWS servers",
      "Newer clouds like Fly / Remix",
      "Nginx and reverse proxies",
    ],
  },
  {
    title: "Projects",
    topics: [
      "GSoC Project setting up and issue solving",
      "Building Paytm / Wallet End to End",
    ],
  },
];

export default function WebDevRoadmap() {
  return (
    <div className="space-y-8 p-4">
      <Accordion type="single" collapsible className="w-full">
        {webDevRoadmapData.map((category, idx) => (
          <AccordionItem key={idx} value={category.category}>
            <AccordionTrigger>
              <p className="text-lg font-semibold text-white md:text-xl">
                {category.category}
              </p>
            </AccordionTrigger>
            <AccordionContent>
              <CardContent className="space-y-4">
                {category.items.map((item, itemIdx) => (
                  <motion.div
                    key={itemIdx}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: itemIdx * 0.1 }}
                    className="bg-brand/30 flex items-start space-x-3 rounded-lg p-3"
                  >
                    <HugeiconsIcon
                      icon={ArrowRight01Icon}
                      size={20}
                      className="mt-1 flex-shrink-0 text-white"
                    />
                    <div>
                      <p className="font-semibold text-white/80">
                        {item.title}
                      </p>
                      <p className="text-sm text-white/35">
                        {item.description}
                      </p>
                    </div>
                  </motion.div>
                ))}
              </CardContent>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      {/* Harkirat 0-100 Syllabus — text version replacing the SVG image */}
      <div className="glass-card rounded-2xl p-5 sm:p-6">
        <h2 className="mb-1 text-lg text-white">
          Harkirat Singh&apos;s 0-100 Syllabus
        </h2>
        <p className="mb-5 text-sm text-white/35">
          A comprehensive full-stack path from foundations to deployment.
        </p>

        <div className="flex flex-col gap-0 divide-y divide-white/[0.06] sm:flex-row sm:gap-0 sm:divide-x sm:divide-y-0">
          {syllabus.map((phase, idx) => (
            <div
              key={idx}
              className="flex-1 px-0 py-4 first:pt-0 last:pb-0 sm:px-4 sm:py-0 sm:first:pl-0 sm:last:pr-0"
            >
              <p className="text-brand-light text-sm font-medium">
                {phase.title}
              </p>
              <ul className="mt-3 space-y-1.5">
                {phase.topics.map((topic, tIdx) => (
                  <li key={tIdx} className="text-xs text-white/40">
                    {topic}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-5 flex flex-col items-center gap-2 sm:flex-row sm:justify-between">
          <p className="text-xs text-white/25">
            Credit: Harkirat Singh — Cohort 2.0
          </p>
          <a
            href="https://harkirat.classx.co.in/new-courses/8-live-0-100-complete"
            target="_blank"
            rel="noopener noreferrer"
            className="btn-primary text-sm"
          >
            Check out the Course
          </a>
        </div>
      </div>
    </div>
  );
}
